# Generated by Django 5.2.12 on 2026-04-02 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_alter_materia_id_alter_perfil_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_equipo",
                    models.CharField(
                        choices=[
                            ("laptop", "Laptop"),
                            ("regleta", "Regleta eléctrica"),
                            ("televisor", "Televisor"),
                            ("otro", "Otro"),
                        ],
                        default="laptop",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_inventario",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código de inventario"
                    ),
                ),
                (
                    "id_unefa",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID UNEFA"
                    ),
                ),
                (
                    "marca_modelo",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Marca/Modelo"
                    ),
                ),
                ("procesador", models.CharField(blank=True, max_length=100)),
                ("ram", models.CharField(blank=True, max_length=50)),
                ("almacenamiento", models.CharField(blank=True, max_length=100)),
                (
                    "sistema_operativo",
                    models.CharField(blank=True, max_length=100, verbose_name="S.O."),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Número de serie",
                    ),
                ),
                ("ubicacion", models.CharField(blank=True, max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("operativo", "Operativo"),
                            ("reparacion", "En reparación"),
                            ("baja", "Dado de baja"),
                        ],
                        default="operativo",
                        max_length=20,
                    ),
                ),
                (
                    "observaciones_generales",
                    models.TextField(
                        blank=True, verbose_name="Observaciones generales"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "ordering": ["tipo_equipo", "codigo_inventario"],
            },
        ),
        migrations.CreateModel(
            name="Mantenimiento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_accion",
                    models.CharField(
                        choices=[
                            ("instalacion", "Instalación de software"),
                            ("limpieza", "Limpieza"),
                            ("reparacion", "Reparación"),
                            ("mantenimiento", "Mantenimiento preventivo"),
                            ("otros", "Otros"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de acción",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                ("tecnico", models.CharField(max_length=100)),
                (
                    "piezas_cambiadas",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Piezas cambiadas"
                    ),
                ),
                (
                    "proxima_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima revisión"
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="Observación"),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mantenimientos",
                        to="usuarios.equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantenimiento",
                "verbose_name_plural": "Mantenimientos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_salida", models.DateField(verbose_name="Fecha de salida")),
                (
                    "motivo",
                    models.CharField(
                        help_text="Ej: Jornada de carnetización, Préstamo a otra aula",
                        max_length=200,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "responsable_recibe",
                    models.CharField(
                        max_length=100, verbose_name="Persona o entidad que recibe"
                    ),
                ),
                (
                    "fecha_retorno",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de retorno"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamos",
                        to="usuarios.equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préstamo",
                "verbose_name_plural": "Préstamos",
                "ordering": ["-fecha_salida"],
            },
        ),
    ]
