# Generated by Django 6.0.2 on 2026-03-15 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Laboratorio')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación (Piso/Pasillo)')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad de Estudiantes')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='¿Está operativo?')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unefa', models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('nombre_equipo', models.CharField(max_length=100, verbose_name='Nombre/Descripción')),
                ('estado', models.CharField(choices=[('OP', 'Operativo'), ('DA', 'Dañado'), ('RE', 'En Reparación')], default='OP', max_length=2)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='usuarios.laboratorio')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('seccion', models.CharField(max_length=20)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
    ]
